<a href="https://colab.research.google.com/github/davidAcode/davidAcode.github.io/blob/master/Dave_teaches_how_to_create_NN_on_Github_02142019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The best teacher is the person who just learned yesterday the stuff you are studying today, because she remembers what she struggled with and how she overcame it, and she can pass those shortcuts on to you.

The best way to master Deep Learning is to master the fundamentals, build a neural network (NN), and then memorize the code, because then you can apply these fundamentals to any NN you meet in future academic papers or work projects.  It all starts here.  Today we will build a NN that can learn by trial-and-error: make a prediction, learn from its mistakes, and do better next time.  Our NN will solve a simple binary classifaction problem, i.e., "given these 1's and 0's in the matrix X as inputs, what is your prediction of the 1's and 0's in matrix y will be?"

Thanks to super-teachers Andrew Trask and Siraj Raval, today's material--a working neural network in about 15 lines of Python--is the foundation of what you need to progress towards an understanding of the cutting edge techniques being used in deep learning today.  My mentor Adam Koenig, a Stanford PhD in aerospace engineering, helped me learn this stuff, and now I'm going to stand on these teachers' shoulders and help you learn it too.

I am grateful for Andrew Trask's [blog post](http://iamtrask.github.io/2015/07/12/basic-python-network/) from which the code below is taken.  

I suggest you open this blog post in two side-by-side windows and show the code in the left window while you scroll through my explanation of it in your right window.  First, I'll show you the entire code we'll be studying today, and underneath that is my detailed step-by-step explanation of what it does.  Get ready for the wonder of watching a computer learn from its mistakes and recognize patterns!  We're about to give birth to our own little baby brain... :-)

Here's the code first.  Display this in your left window:


In [0]:
#This is the "3 Layer Network" near the bottom of: 
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#First housekeeping: import numpy, a powerful library of math tools.
import numpy as np
#1 Sigmoid Function: changes numbers to probabilities and finds slope to use in gradient descent
def nonlin(x,deriv=False):
  if(deriv==True):
    return x*(1-x)
  
  return 1/(1+np.exp(-x))
#2 X Matrix: This is a set of inputs in the training set that we will use to 
#train our network.
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
#3 y Vector: The output layer: Our training set of 4 target values. Once our NN
#can correctly predict these 4 target values from the inputs provided by X, 
#it is now ready to predict in real life.
y = np.array([[0],
             [1],
             [1],
             [0]])
#4 SEED: This is housekeeping. Ya gotta seed the random numbers we will generate
#in the training process, to make debugging easier.
np.random.seed(1)

#5 SYNAPSES: aka "Weights." These 2 matrices are the "brain."  It remembers, learns, improves.
syn0 = 2*np.random.random((3,4)) - 1 # First layer of weights, Synapse 0, connecting l0 to l1.
syn1 = 2*np.random.random((4,1)) - 1 # Second layer of weights, Synapse 1 connecting l1 to l2.

#6 FOR LOOP: this iterator takes our NN through 60,000 guesses, tweaks, and improvements.
for j in range(60000):
  
  #7 FEED FORWARD NETWORK: Think of l0, l1 and l2 as 3 matrices as the "neurons" 
  #that combine with the "synapses" matrices in #5 to think, predict, improve, remember.
  l0=X
  l1=nonlin(np.dot(l0,syn0))
  l2=nonlin(np.dot(l1,syn1))
  
  #8 TARGET, and how much we missed it by. y is a 4x1 vector containing our 4 target 
  #values. When we subtract the l2 vector (our first 4 guesses) from y, our target,
  #we get l2_error: how much our neural network missed the target by on this iteration.
  l2_error = y - l2
  
  #9 PRINT ERROR: in 60,000 iterations, j divided by 10,000 leaves a remainder of 0
  #only 6 times. We're going to check our data every 10,000 iterations to see if
  #the l2_error is reducing, and we're missing our target by less each time.
  if (j% 10000)==0:
    print("Our average l2 error after 10,000 more iterations: " + str(np.mean(np.abs(l2_error))))

  #10 In what DIRECTION is y, our desired target value, from our NN's latest guess? We
  #take the slope of our latest guess, multiply it by how much that latest guess
  #missed our target of y, and the resulting l2_delta tells us by what value to update
  #each weight in our syn1 synapses so that our next prediction will be even better.
  l2_delta = l2_error*nonlin(l2,deriv=True)
  
  #11 BACK PROPAGATION: After we "fed forward" in Step 7, no we work backwards to 
  #find the l1 error.  l1 error is the difference between the ideal l1 that would 
  #provide the ideal l2 we want and the most recent computed l1.  To find l1_error, 
  #we have to multiply how much our latest prediction missed the target (l2_error) 
  #by our last guess at the optimal weights (syn1). We'll then use l1_error to update syn0 below.
  l1_error = l2_error.dot(syn1.T)

  #12 In what DIRECTION is l1, the desired target value of our hard-working middle layer 1,
  #from l1's latest guess?  Similar to #10 above, we want to tweak this middle layer
  #so it sends a better prediction to l2, making it easier for l2 to better predict target y.
  
  #AK: I don't think l2 should be mentioned here.  It is similar to what was 
  #done before.  Add weights to produce large changes in low confidence values 
  #and small changes in high confidence values
  l1_delta = l1_error * nonlin(l1,deriv=True)
  
  #13 UPDATE SYNAPSES: aka Gradient Descent. This step is where the synapses, the true
  #"brain" of our network, learn from their mistakes, remember, and improve--learning!
  syn1 += l1.T.dot(l2_delta)
  syn0 += l0.T.dot(l1_delta)

#Print results!
print("Our l2 error value after all 60,000 iterations of training: ")
print(l2)

l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
syn0
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
l1
[[0.44856632 0.51939863 0.45968497 0.59156505]
 [0.28639589 0.32350963 0.31236398 0.51538526]
 [0.40795614 0.62674606 0.23841622 0.49377636]
 [0.25371248 0.42628115 0.14321233 0.41732254]]
syn1
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]
l2
[[0.47372957]
 [0.48895696]
 [0.54384086]
 [0.54470837]]
l2_delta
[[-7.51235207e-06]
 [ 7.55068179e-06]
 [ 6.74174863e-06]
 [-8.00425612e-06]]
l1_delta
[[ 9.46832171e-10 -3.08497572e-05  5.08949926e-05 -3.15810072e-05]
 [-5.49981023e-05  9.22271485e-11 -1.98772953e-05  4.06826431e-05]
 [-5.58922384e-05  4.01319985e-05 -2.09610752e-05  8.85971300e-11]
 [ 7.74711336e-05 -1.94497871e-05  8.78140259e-11 -1.97665444e-05]]
Our average l2 error after 10,000 more iterations: 0.4964100319027255
l0
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
syn0
[[  

Now, let's go through each step of the code in detail:

#1) The Sigmoid Function: lines 6-11:

"nonlin()" above is a type of standard logistic function known as a Sigmoid function.  Logistic functions are very commonly used in science, statistics, and probability.  This Sigmoid function is written in a more complicated way than necessary because it serves two functions:

1) to take each of the matrices within its parentheses and convert each value to a number between 0 and 1 (aka a statistical probability).  This is done by line 11: `return 1/(1+np.exp(-x))` 
We will see below that this is very important, because this conversion to a 0-1 number gives us **FOUR** very **big advantages**.  I will discuss these four in detail below, but for now, just know that the sigmoid function converts every number in every matrix within its parentheses into a number between 0 and 1 that falls somewhere on the S-curve illustrated here:

![alt text](https://iamtrask.github.io/img/sigmoid.png)

(taken with gratitude from: 
[Andrew Trask](https://iamtrask.github.io/2015/07/12/basic-python-network/))

So, Part 1 of the Sigmoid function has converted each value in the matrix into a number between 0 and 1, i.e., a statistical probability, which is also known as a confidence measure.  In other words, the number answers the question, "how confident are we that this number correctly predicts an outcome?"  

Now for Part 2.  The second part of this sigmoid function is in lines 8 and 9:
'  if(deriv==True):
    return x*(1-x)'
When called to do so by `deriv=True` in the code below, line 9 takes the confidence measure from Part 1) and converts it into a slope of the Sigmoid S curve, which will be used to tweak the synapse matrices of our NN and nudge them towards greater accuracy in prediction.  

So the sigmoid function plays a super-important role in making our NN learn, but don't worry if you don't understand it all yet.  I'll explain it in detail below.  Let's move on to Step 2:


#2) Creating X input: Lines 12-17
Lines 12-17, step 2, create a 4x3 matrix of input values that we will use to train our network.  X will become layer 0, or l0 of our network, so this is the beginning of the "toy brain" we are creating!  

Think of each row of this matrix as a training example we'll feed into our network, and each column is one node of our input.  So our Matrix X can be visualized as this:

![alt text](https://lh3.googleusercontent.com/1cxj3K8bj_IOL8lhF9pRQSbDQyo3imZGVmZlEsjfvX1ImXBIJZHeJgOtX2kOQoaEbfhCbqtR2JFzSXK_r41dGGVdH6rde7QgoIqEGGn-v37CcD6IWw-nk9put1txPGeKvP-fxo3Lwk3nlwd3nkIdgjMu8HQf9ccyAZGlgRj7YH3avElDzwJr6kEDygOaLxmR9xo427aQHMwSjhdQKrrHwfTSsrUZmXyKh5F2anucPUAB-BAfTNyIG4brluYZwwKq3Mhx4eOJkn51V0D4zlcDVDPEK7k789ZUYVSfEcJ4_QbIY7YVeSHkqO-jQ3XB6XeK1WydnTFF8-OcOgBEzuKB6LDUNUYttH8eKE-k7OB5vi7h56PmIK35-ciOix52zaQRP0s8kcBeL5NAimjhIZjC6j5Am7CAf7VeBZUs9q9UvemlNYRZze_SWmlJIQBVx05GOShiGlHXAYZxdEWSOT9P4B09RmeqVCxakgQbgzOpS-05KVFzcIDn8HYsKOLj05uURaLfPL8AP3kKEOSE4z3iSdBxVnRuu6taQcRBU9q9UbZbdo7z0vXPbacLuxc1nPlvOkb_0fcHQxqU1Dn-i17fBUeV1Mcv_sjxhvXzvlVJq3qhJAyYD5YYDi0AgLLIU-o2XZ31DGFkvNQxioM8mPT5tOeycr-n4sfS=w518-h389-no
)

Notice that I have turned the 4 rows (aka 4 training examples) onto their sides to make 4 columns.  I don't mean to confuse you. It is very important to visualize matrices as nodes, and you will see why below.  But first, we have to do some housekeeping and create the other parts of our NN.  Next: creating our output layer, also known as our target values:

#3) Create y output: Lines 18-24
This code creates our output layer: Our training set of 4 target values. Once our NN can correctly predict these 4 target values from the inputs provided by matrix X above, it is now ready to predict in real life.  Think of X, the input layer, layer 0, as the beginning of our NN.

![alt text](https://lh3.googleusercontent.com/JIjq0M7KAMEa8MkGResGW3R86x_CPJ1vskRyou_niy0ezQA-QH1dtbgHHZm8Jcu1uJhd6o-ZgVKgGQaYycGh-PWfCU-xgg6HGWRi_JtQiWPr764p1hsd76UWLiYtl3A1oJcTZKHiUU1q6l4LGpOYwRMnTMMT0fFqLjyq4EFZk3d16DYZeg541WcZMhqDLPJ1SpioL36phy_y-upXNzw464WhSHD5On-DBDbvpDWsxbE87Fhp6AXptRMrbHeOiZEmMsU6U9bdS0GWKJDJ1LEQuHb4d5hQevHFKUW-8RUnTC7Qu-Nx9WyleDaQYeNNmd-Gq79jMFcebQ4CwFwgUU3a19E7SrnecoBUqxCjNVJbOhowOmuVvHVgwULhQxKcH49IKRFjIJO0ZC80UNnjnq6drN7XrHPZDVhwV5cmyTTIMe0xUuxiGKBAI2VI0TZZkd7KxSeWIOx82qsTnbLRilYDUlqHZ43-H7DnJugCaHY9gi7uv0XnBMbaYTj58M-dcbLMEAhGjgro433DD1b9WJ7olKQOTpyzVO7OgTafUHV5kvdzA-o1KYFECaIh1EPDJu3FRDxYlLFC44yXGMQA7CXIcW2fKT02uviulyqk3Rfh-8LgqhzGSjQRX7pS7XCkcrL1AOikPCh9J3T_0c_caMri33b2J7Uezev6=w968-h703-no)

y, the output layer, is the end:
![alt text](https://lh3.googleusercontent.com/6J6pt5FDEceBFHqP18HZ3rdWE3oRHhOlFG2ZAeng6vROeQZuLajnYrCw2oAmPv39yYnDHi2R1K91kF1B9fyAZePNaTcZhyxOiW7U1MPeQUyBcMWH02wT4yrVyWIHn9Yz8vXlASd9G14mVgoxTvRvWtDBsQlVwf2gn48TLy3Xm7Z7JepB5X0yk_xusS5-7nwtspG8NkKQwVrJjCEzwR6wAN5KgUfFd15r1RI-6Hwb082hcipNWl5TX8pqvNdrMkrOjYHnNexc-CUGwIESRd3ramL72W4Wb1B8WciircrSFlt3bHRNO_11ZVB5W061dOhV8O9xhmPRiFQQImS99UpbK7Lwuu5FG4hLyr6rYPJsyMsMlT5yOsSjlypBTrKEJq8USJJmsPrGdbQ_hKtwuo-ywnmOTS4Bpz0eSI_JxNfzV4hFN4uo9LxcLqlSvUBH72HlDlPSsMpyMroieRJifYraW6XXpeZ__DXSbxWkm9oz4x-W1YJNQV_pljbHEEHTv4iGS22YyyLd84gPYoagm74ptwXodx2jJi9KHy2E_2HBvpVmQVgVgNFZq7-JO13PzzSOhhpT57EzBr1ToMbjRAaNl4KHCBjJY-5-l7mE1Q5-NTtMH5MV219sPi4za2Fq06hfDmJKMKDei1BgFxkczdmr92PdCm4-98z9=w518-h388-no)

AK, am I correct that the above is only 1 node?


#4) Seed your random numbers: Lines 25-27
This step is housekeeping. We have to seed the random numbers we will generate in synapses/weights for the next step in our training process, to make debugging easier.  You don't have to understand how this codes works, you just have to include it.

#5) Create "Synapses" of your brain--Weights: Lines 29-31
These 2 matrices are the "brain" of our NN.  These layers are the part of our NN that learn by trial-and-error making predictions, then improve their next prediction, then remember their improvements--learning!

![alt text](https://lh3.googleusercontent.com/S-ihGzoU2SJQvm36_2f0ORWDmJFe-gs2tjVB-MEZgKXAfhpLzwroAg7x7w7ynCDbycJtytdC5KmRTj0yNQ0mFBYLgE26L7CTl8HeZfjXnqOQkPqyR0tWRSmKg2VxscEEwmhEAu06kmI4YddkLXVIqx0cjPcuLqQSdOfprAUbH661aB5-H5XPdkiW83RCRGUYvUYZM0rpQhJM3LuV8jAO9ZEO3il87MQEahMKOPrsNp2KWsbDX9HF3B17_cz_ZyYRa7to30FdKOaOxL1R8ccFOzGHfEtfv5B5AuBX8Nqxq6LV-j1DSU_OTosxenEY238Bpc8aUnTLniN6T65YLQ1Re17yK28z3B-Mcc4OHsRYHObk2pZU7ASedCSO8SgW4pUyT1IJZpei0wNGLYRi50kLCgDraQr07aDodr-HpkP7jRAQcEFNWnFGPNsvA3sQz4QT2wZhEx9kVJLZdVHEsglCE1_bzdzKnE3MPv0QNAz72juBmicCxcNEv_p-BAlQsvkDrES1QdIn0PTXJAo8Wd2f1RndNWqdxlA4qBU1cwhNPjouv1CFbAQnDL9IiwbeXFD5AUjL4jDDUZYt8MGwZ1Mg6YGakLOWz-RZ05uitJFtQSV-UgC4tZ6K02kbLbv-8JYDK5-JoRfap6S6JeTapIa_nf_f1IFg397-=w968-h238-no)

Notice how this code, `syn0 = 2*np.random.random((3,4)) - 1` creates a 3x4 matrix and seeds it with random values.  This will be the first layer of weights, Synapse 0, that connects l0 to l1.  You'll visualize it below in a minute.

The function np.random.random produces random numbers uniformly distributed between 0 and 1 (with a corresponding mean of 0.5).  But we want this initialization to have a mean zero.  Why?  So that the initial weight numbers in this matrix do not have an a-priori bias towards values of 1 or 0, because this would imply a confidence that we do not yet have (i.e. in the beginning, the network has no idea what is going on so it should display no confidence until we update it after each iteration).  

So, how do we convert a set of numbers with an average of 0.5 to a set with a mean of 0?  We first double all the random numbers (resulting in a distribution between 0 and 2 with mean 1) and then we subtract one (resulting in a distribution between -1 and 1 with mean 0).  That's why you see `2*` at the beginning of our equation, and - 1 at the end: `2*np.random.random((3,4)) - 1`

Notice that we are generating a 3x4 matrix.  Why?  Because l0 (aka our X matrix) is a 4x3, and matrix multiplication requires the inner 2 size numbers to match, i.e., a 4x3 matrix must be multiplied by a 3x_?_ matrix--in this case, a 3x4.  See how those inner two numbers must be the same?

Then this line of code, `syn1 = 2*np.random.random((4,1)) - 1` creates a 4x1 vector and seeds it with random values.  This will be our NN's second layer of weights, Synapse 1, connecting l1 to l2.  Keep an eye on the size of each matrix we are creating, because this will become *very* important soon.



#6) For Loop: Lines 33-34
This is a for loop that will takes our NN through 60,000 iterations.  For each iteration, our network will take X, our input data, and based on that data, give its best guess at a prediction of what our y output is. It will then analyze how it did, learn from its mistakes, and give a slightly better prediction on the next iteration.  60,000 times, until it has learned by trial-and-error how to take the X input and predict accurately what the y output is.  Then our NN will be ready to take *any* input data you give it and correctly predict its future!


#7) Feed Forward Network: Lines 36-40
This is where our NN makes its first guess at a prediction. Think of l0, l1 and l2 as 3 matrices that are the "neurons" that combine with the "synapses" matrices we created in #5 to think, predict, improve, remember.  This is where matrix multiplication becomes key.

First, on line 39 we take the dot product of the 4x3 l0 and the 3x4 Syn0 to create (hidden layer) l1, a 4x4:
![alt text](https://lh3.googleusercontent.com/Qbej-Y21C2su8KnB4dzus7l39oJ8c1VZ-3oLOJLqWrb6sr_pAjyq2vBPJ8Y8VG8JPaQQKOybzyTo7sqgDI6OPdd24VAR71aMXSzXRpaPpxLsYwgvEhWJxC0CwtUIlJp5Xjar-jvUMBrybLnnsbhJ9s-cf1Exci0nlUNFCiFjtH1O5SdST71fPXhZoUUOxN9-hWv6Msr5Obpg0ve5RrZc_VvSGD9I85nqxRvpaILZkQQLeggj4tlBW528lymNR9e28gwOy9fuAopRaM37Mfw0or9aIZiK4jjiSuU0FoHX757Mv0JgvmM6QgVOb2sNxpX6Lx2eASFX6nxctGwXW0hX1wnzZRRf_KttjjeOTSa6r70KZdKy3f8RH4JK3oxroGBI4RXWOaSwNHHgmd7ljoo0uvUmKy3ScE0cMummCWfTNAv8dcvvi53JqbixVglUL_DQ-v-P4ZyW5HY2xJTWZ8KgByme0FlZTQFURPkvHFw7g375kI3Ad188o5L9p30SlvyKZ_N5Dp2VXHS5cavs42-OVWY47v0fYijR8VpPBOAfWNrcVAn1jOO_YLOwv7z3VFc8RbyMSoAFve0b3m6qGNHh-oYvpVhAuelaUzRWb5x0HYSLUq-wQZRksy8klBo2LWhQxsYTFoZSKLocyNj83uBnCd5-lrAve-SU=w968-h594-no)


Notice that line 39 uses the `np.dot()` syntax because we are taking the dot product of two matrices.  Later we'll use the simpler multiplication syntax, i.e.,`(*)` when we are simply multiplying two vectors.  But you must be clear on the size of matrices you are multiplying in order to use the right syntax.

Still on line 39, we next take the Sigmoid function of l1 because l1 may have values between 1 and -1, and we need it to have values between 0 and 1, hence: `l1=nonlin(np.dot(l0,syn0))`

It is on line 39 that we see ***Big Advantage #1*** of the ***Four Big Advantages of the Sigmoid Function.***  When we pass the dot product matrix of l0 and syn0 through the `nonlin()` function, the sigmoid converts each value in the matrix into a statistical probability between 0 and 1.  This means, "the closer the value is to 1, the more certainty there is that such-and-such is the case, whereas the closer the value is to 0, the more certainty that such-and-such is NOT the case.  "So, what?" you may ask.  Well, it doesn't matter in lines 39 and 40, but it matters a *ton* when we hit line 61 and beyond.  Stay tuned.

Exactly the same thing happens on line 40, as we take the dot product of 4x4 l1 and 4x1 syn1 and then run that product through the Sigmoid function to produce a 4x1 l2 with each value becoming a statistical probablility from 0-1.

![alt text](https://lh3.googleusercontent.com/3J2E3TRyLA2YCqF6XcHXn22e1qb_8U-2OTVUGZmgPjm1Y4AiAwOjID8CVP1tpRC2vKKWX2Sk3gQtA0Efxq7dURbFjirsdSFJJPJ3G1pH0LHh771mGRqr7DHNQ7521JxpdFiyhP5jCA8_K-mtRdctF316SRtg9M9Ni0TNuR4FonhSjZmI2oP1o9azJdmsoyEVHhJF6TcsdNllYoNGlsgioEwaIidkm2B6a8L-TEkRJjYc6nzJzTG0Z8uQcrxl5xpCrj-YO-F2r8a0gMZur0w1NJm6LLA1kbMDipdGk9IiDbxwLpNd-9jyLiFZRsOZsc2SB18-TCjWSO0oqXlLTr86XtDPp2Xh-fKseNWeFYmjyWIEY20DI7ggDr2jJgLrOR-kJPA9hMpk_xOHOyWgYfn3XF7QPnO_bKUsvLJ0FPUyICsAV1IVQQm0e-K7QdDmRRHioE7Ri4NOt-3THjBi3D4P3pCtzha9aSqxNG3F2AXKb4ziD3Dm0GBei-EY3Vjoa4J--0XRwSH96L2unpiiv5cpPbyGXvraWvHb1ODdPiD73xDLH1R457gFTccsLq0Fuq0b510mDaFi_zIdCME8_ifdgNxj9oSBSo7U690-BKb6svQEz3LEyQnDrcBhEHZW6bSN3H1JAQvUmurC8ylt1BzBgZimM3EFzH7h=w968-h632-no)

Now we have completed the Feed Forward portion of our network.  This would be a good time to visualize what we have done so far, both in terms of the matrices involved, and also the layers of "neurons" and the "synapses" connecting those neurons:

![alt text](https://lh3.googleusercontent.com/Rsh6bYtBEu_oAMLVXppmxO0ayEBDJVQg8YwDZGz0_I6JKB588v5aVQbzQKrx-srfY1sGZm4V83NuSIPxaWBntZH3Hm584xbax4RR0f3L5IAOLSB3jH5ZNXJnnhl7gAQR9w2UsqOuxsdoRDXj1xrmLZkC_ZCEZrooNcHJRpEPySTsTiTb61j9AQg-uH2TLUewt02YPshI4i0f3Ynoc9IHa6IgywBH_k_Baae6FcOIuTPApdSiLDviMoZuIZLMOdGusJ1oV_E4sl7wWHcr4JQOlpz8rGArnyLkUywKh_1BJigH_z8s1EcUuA6NfUY8W_4qGJsEqLKDac2hhvvgqoUQTiLqis7PKp_8eS-MjpSv5tz17gclQAj4snNmlF_gEKLWMgRuPVju1zGmoMZeMPqMnXDE-QWVVAIKFYwtCe83KELSDKmkRCI_hySi0MYualR9tL7EPRdSjpS6VWoChupgnHodSdPKmNkx7qcGI8vE-BMWiVzxC1gxICM9DUc5h7LCAkwR2p4tN94tQB8z12AxI5-TI8l_tT1-RvgrhqO5QJv2tBzud7P6rJBUZxSVHqCt4wlP4ZbVgAviCwJDpzLzbsI3HE9666hHMNZLcUqsTd2YRwaV-p7m8DTcDmy4IzB36qNMDSNip8VG4CunowqCbQlw6kXBzVYp=w968-h698-no)





#8) By How Much Did We Miss the Target? Lines 42-45
The 4x1 y vector is our goal, our target.  Given our input X of layer 0, we want to produce an output, layer 2, that is as close to the 4 values of y as possible.  Each one of our 60,000 iterations should bring us, by trial-and-error and learning from our mistakes, closer to the 4 target values of y.  So, for each iteration, we take our best prediction so far, the 4x1 vector l2, and subtract it from the 4x1 vector y.  The remainder is l2_error, i.e., how much each value of l2 missed its target value in y.  

This is the exciting first step in the learning process of our NN.  Once we know what we missed by, in the following steps we will seek to correct that error and do better next time.

#9) Print Error: Lines 47-51
Line 50 is a clever parlor trick to have the computer print out our l2_error every 10,000 iterations.  The line, `if (j% 10000)==0:` means, "If your iterator is at a number of iterations that, when divided by 10,000, there is no remainder, then..."  ` j%10000 `would have a remainder of 0 only six times: at 0 iterations, 10,000, 20,000, and so on to 60,000.  So this print-out gives us a nice report on the progress of our NN's learning.

The code `+ str(np.mean(np.abs(l2_error))))` simplifes our print out by taking the absolute value of each of the 4 values, then averaging all 4 into one mean number and printing that.

#10) In What DIRECTION is y?  Lines 53-57
Now we have entered the brain of the beast; here is the secret sauce of Deep Learning.

You might call Step 10, "How much do I tweak my NN before its next iteration and prediction?"  For statistics and calculus buffs, we could simply say, "In line 61 we compute how much the l2_delta needs to modify the error with weights from the derivatives to induce large changes in low confidence values and smalll changes in high confidence values."  Whew!  For the rest of us mere mortals, let me unpack that a bit:

First, let me give you an overview of what we're going to do:
1) In line 45, we find l2_error, which measures how much our first prediction, l2, missed the target values of y;
2) In line 61, we use l2_error to calculate by how much we need to adjust the weight values in our syn1 matrix in order to make a better prediction next time.  l2_delta = "how much to change the weights in line 81."  
3) Rinse and repeat: in line 68, we will find the l1_error and use it in line 77 to calculate the l1_delta by which we should change syn0 in line 82;

Now, the details:

Here is where you will see the beauty of the Sigmoid function in four *magical* steps.  To me, the genius of neural networks' ability to learn is found largely in these four steps.  We saw how, in line 39, Step 1 was when the `nonlin()` transformed each value of our matrix into a statistical probability between 0 and 1.  But I have yet to mention that that statistical probability is ***also*** a simple measure of confidence--numbers approaching 1 suggest high confidence that the NN's (neural network's) prediction is correct.  Numbers approaching 0 suggest high confidence that the NN's prediction is incorrect.  But what matters here is ***confidence.***  If our NN's prediction, the four values of l2, is high-confidence and high-accuracy, that's an oustanding prediction, and we want to leave the syn0 and syn1 weights that produced that oustanding prediction alone.  We don't want to mess with what's working; we want to fix what's NOT working.

That's why we focus our attention on the numbers in the middle:  all numbers approaching 0.5 in the middle are wishy-washy, and lacking confidence.  So, how can we tweak our NN to produce four l2 values that are both high-confidence and high-accuracy?  

The key lies in the values, or ***weights*** of syn0 and syn1.  As I mentioned above, syn0 and syn1 are the center, the absolute *brains* or our neural network.  We are going to take the four values of the l2_error and perform beautiful, elegant math on them to produce an l2_delta.  l2_delta means, basically, "the amount by which we need to increase-or-decrease our weight values in syn0 and syn1 in order to reduce wishy-washyness and maximize the high-confidence, high-accuracy values of the prediction of our next iteration."

***Get ready for beauty.***

Here is ***Big Advantage #3*** of the ***Four Big Advantages of the Sigmoid Function:*** Do you remember that diagram of the beautiful S-curve of the Sigmoid function that I showed you above?  Well, lo-and-behold, each of the 4 probability/confidence values of l2 lies somewhere on the S curve of the sigmoid graph (pictured again below, but this time with more detail).  If we search for that number (e.g. 0.9) on the Y axis of the graph below, we can see that it corresponds with a point on the S curve roughly where you see the green dot: ![alt text](https://iamtrask.github.io/img/sigmoid-deriv-2.png)
(taken with gratitude from: 
[Andrew Trask](https://iamtrask.github.io/2015/07/12/basic-python-network/))

Did you notice not only the green dot but also the green line through the dot?  That green line is meant to represent the slope of the *tangent* to the line at the exact point where that dot is.  You don't need to know calculus to take the slope of a curve at a particular point--the computer will do that for you.  But you do have to notice that the S curve above has very shallow slope at both the upper extreme (near 1) and the lower extreme (near 0).  Does that sound familiar?  Wonder of wonders, a shallow slope on the sigmoid curve coincides with high confidence and high accuracy in our predictions!  And you also need to know that a shallow slope on the S-curve comes out to a tiny number for slope.  That's good news.  Why?

Because, when we go to update our synapses, we basically want to leave our high confidence weights alone since they already have good accuracy.  To "leave them alone" means to multiply them by tiny numbers, near zero, so the values remain virtually unchanged.  And, miracle-of-miracles, because our high-confidence numbers correspond to shallow slope on the S-curve, which corresponds to tiny slope numbers, therefore multiplying the values of syn0 and syn1 by these teeny-tiny numbers has exactly the effect we want: the values in our synapses are left virtually unchanged, so our confident, accurate, high-performing values in l2 remain so.

The other good news is that our wishy-washy, indecisive, low-accuracy l2 values, those corresponding to points in the middle of the S-curve, are the numbers that have the biggest slope on our S-curve.  What I mean is, the values around 0.5 can be traced on the Y axis of our graph below to the middle of the S-curve, where the slope is steepest, and therefore the value of that slope is a big number.  Those big numbers mean a big change when we multiply them by the values in l2, as we do in line 61.

When we update our synapse matrix by multiplying the corresponding element with that large slope number, it's going to give that element a big nudge in the right direction towards confident and accurate prediction.  When I say, "in the right direction," what I mean is that some values of our l2_delta are going to be negative, because we want them to reduce the weight values closer to 0 in syn0 and syn1.  Other values of our l2_delta are going to be positive, because we want them to increase the weight values closer to 1 in syn0 and syn1.  

So it's important to notice that there is a sense of "direction" involved here.  When we talk about "what direction is the y value from our current l2 value?" we mean, do we need to multiply each weight in syn1 by a positive l2_delta value to move it in a positive, larger direction, or by a negative l2_delta value to move it in a negative direction?

Have you heard of gradient descent?  Gradient descent is all about direction.  It is often described as, "a ball dropped in a bowl and rolling in a **back-and-forth direction** until it comes to a rest at the global minimum, the bottom of the bowl."  That's what the Sigmoid does for us.  It helps us to find the bottom of the bowl, which is the minimum of the cost function, which is the lowest error in our predictions.  Think of our 60,000 iterations as the ball rolling in a back-and-forth direction in the bowl until it no longer needs to change direction because it has come to rest at the ideal, perfect bottom of that bowl.  Picture it like this:

![alt text](https://mail.google.com/mail/u/0?ui=2&ik=e3f869f938&attid=0.2&permmsgid=msg-a:r4352876950048414936&th=1691255aa52a4d54&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ8FdFORGv3w0jn-Bs8GhlKpg2D1XPRzSF6OaNCqE8hchNYMIAymIg-nK1xCdIsQup54rJmkW2l0qttCzg03Hq8PJOv4KX0ae14e2dkswvLMt74Rzdhwt2ZJQBQ&disp=emb&realattid=ii_jsexnu8o2)
(taken with gratitude from [Grant Sanderson](https://www.youtube.com/watch?v=IHZwWFHWa-w&t=2s&index=3&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi) Ch. 2)

Above is a nice, simple picture of the "rolling ball" of gradient descent.  Line 61 computes each value of l2 as a slope value.  A steep slope downwards to the right (i.e., a negative slope value) means our ball will roll a lot in the negative direction (i.e., to the right), causing a big change in the corresponding weights of syn1 to be used in the next iteration to predict l2.  A shallow slope downwards, say, to the left means that that prediction value is already accurate and confident, which produces a tiny, positive slope value, so the ball will roll very little to the left (i.e., in a positive direction), thus changing by very little the corresponding weight in syn1, so the next iteration's prediction of that value will remain largely unchanged.  This makes sense because the rolling ball will soon come to rest at the global minimum, the bottom of the bowl, so there's no need to move much.  It is already close to the ideal.

The above 2-dimensional diagram is a tad oversimplified, so here's a more accurate picture of what gradient descent looks like:
![alt text](https://lh3.googleusercontent.com/jIup60T65tIKtXg0B-Np6jeNXk4TvQTRgBI1btNRZUZ4yy_ZEyL1bN3RwiSjzKNcbyXQN6z7vdV55NzGFxJfUpZXkyU6HTmrScht0rbk5BXGC6eO79LrZuuVpJdHE4fr4QYwvdbO)
(taken with gratitude from [Grant Sanderson](https://www.youtube.com/watch?v=IHZwWFHWa-w&t=2s&index=3&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi) Ch. 2)

Think of the dotted white line in the diagram as "The Path Towards Accurate Prediction."  Each dot of that dotted white line represents a tweak, or update of the weights syn0 and syn1, that will take our ball closer-and-closer to the bottom of the bowl, which is the global minimum error, where our NN's predictions are most accurate.

Take your time with the above points and make sure you understand them.  Do you see why the sigmoid function is a thing of beauty?  It takes any random number in one of our matrices and turns it into a statistical probability, which turns into a confidence level, which turns into a big-or-small tweak of our synapses, always in the direction of greater confidence and accuracy.  The sigmoid function is the miracle by which mere numbers in a matrix can "learn." A single number, along with its many colleagues in a matrix, can indicate probability and confidence, and that matrix can learn, and remember that learning, over-and-over again as it improves with each iteration!  Trial-and-error is a thing of beauty.


#11) Back Propogation: Lines 59-64
In Step 8 we found out by how much our prediction, l2, missed our target values of y--the l2_error.  
In Step 10 we used l2 and l2_error to compute by how much, and whether positively or negatively, we should tweak the weights of syn1--the l2_delta.
Now, in Steps 11 and 12, we are going to compute the l1_delta, but in a slightly different manner.  We are going to use back propogation.  For now, think of it as "working backwards."  Here we go: 

First, we find the l1 error.  l1 error is the difference between the ideal l1 that would provide the ideal l2 we want and the most recent computed l1.  To find l1_error, we have to multiply how much our latest prediction missed the target (l2_error) by our last guess at the optimal weights (syn1). We'll then use l1_error to update syn0 below.

Let me see if I can break that down further:

In line 64, we first multiply our "old syn1," the weights used on this current iteration, by the l2_error.  This is indeed working backwards, because it was this version of syn1 that gave us our current l2 prediction, which produced our current l2_error.  So, to multiply the l2_error by the old syn1 allows us to compute by how much the old l1 of this iteration missed the ideal l1.  

Why?  Consider: if the old l1 had been perfect, then multiplying this perfect l1 by the old syn1 would have produced a better l2, with less l2_error.  But the old l1 wasn't perfect, therefore the l2_error is bigger than it could have been, so multiplying it by the old syn1 gives us a clear picture of by how much the old, imperfect l1 missed its ideal l1--the l1_error.  In other words, we learn by how much each value in l1 contributed to each corresponding value in the l2_error.

AK, Trask describes this back proppgation like this: 
l1_error = l2_delta.dot(syn1.T)
The above line of code uses the "confidence weighted error" from l2 to establish an error for l1. To do this, it simply sends the error across the weights from l2 to l1. This gives what you could call a "contribution weighted error" because we learn how much each node value in l1 "contributed" to the error in l2. This step is called "backpropagating" and is the namesake of the algorithm. We then update syn0 using the same steps we did in the 2 layer implementation.
AK, I don't understand what Trask means by, "sends the error across the weights from l2 to l1."  Can you explain?

AK, this is the section where I have the least confidence.  What am I missing?  What should I add?  What diagram would be helpful?

#12) In what DIRECTION is the target (ideal) l1?  Lines 66-69
We will use the exact same process as Step 10 to find in what direction our gradient descent should be moving in order to take us closer to the perfect l1 that will contribute to us finding the perfect l2, our ultimate goal.

We want to answer the question, "In what DIRECTION is l1, the desired target value of our hard-working middle layer 1, from l1's latest prediction in this current iteration?  We want to tweak this middle layer of our NN so it sends a better prediction to l2, making it easier for l2 to better predict target y.  In order to answer this question, we need to find the l1_delta, which tells us how much to adjust the weights to produce large changes in low confidence values and small changes in high confidence values.


#13) Update Synapses, aka Gradient Descent: Lines 71-74
This final step is all the Glory Moment:  all our work is complete, and we reverently carry our hard-earned l1_delta and l2_delta up the steps of the podium to our hallowed leader, Emperor Synapse, the true brains of our operation.  

We update syn1 and syn0 so they will learn from their mistakes of this iteration, and in the next iteration they will lead us one step closer to that ideal bottom of our bowl, where error is smallest, predictions are most accurate, and joy abounds!

AK, why do we multiply the l2_delta by ***l1*** to update syn1?  I would have expected to multiply the *old* syn1 by the l2_delta to update the weights by the corresponding delta in l2_delta, thus creating a new-and-improved syn1 to use in the next iteration.  No?  Why not?
syn1 += l1.T.dot(l2_delta)
syn0 += l0.T.dot(l1_delta)


#In Closing...
Andrew Trask gave me a fabulous gift when he wrote that memorizing these lines of code leads to mastery, and I agree for two reasons: 

1) When you try to write out this code from memory, you will find that the places where you forget the code are the places where you don't understand the code.  Once you understand this code perfectly, every part of it will make sense to you and therefore you will remember it forever;

2) This code is the foundation on which (perhaps) all Deep Learning networks are built.  If you master this code, every network you learn and every paper you wade through will be clearer and easier because of your work in memorizing this code.

Memorizing this code was made easy for me by making up an absolutely ridiculous story that ties all the concepts together in a fairy-tale mnomonic.  You will remember better if you make your own, but here's mine, to give you an idea.  I count the 13 steps on my fingers as I recite this story out loud:

1) Sigmund Freud (think: Sigmoid Function) abolutely *treasured* his neural network, and he buried it like a pirate's treasure, 

2) "X" marks the spot (Creating X input that will become l1).  

3) "Why," I asked him (Create the y vector of target values), "didn't you plant 

4) Seeds instead?" (Seed your random number generator)  "You could have grown a lovely garden of 

5) Snapdragons," (Create Synapses: Weights) "which could be fertilized by the 

6) firm poop" (For loop) "of the deer that 

7) Feed on the flowers" (Feed Forward Network).  Suddenly, an archer 

8) Missed his target (By How Much Missed the Target?) and killed a grazing deer.  As punishment, he was forced to 

9) Print his error (Print Error) on a 500 times on a blackboard facing the 

10) Direction of his target (In What Direction is y?).  But he noticed behind the 

11) BACK of his target two deer were mating and PROPOGATING their species (Back Propogation) and he shouted for them to stop but they wouldn't take 

12) Direction and ignored him (In what Direction is the l1 target?).  He got so angry that his mind 

13) Snapped and he descended into Gradient Insanity (Update Synapses, Gradient Descent).  

So, there is a very silly story, but I can tell you that it has burned those 13 steps into my brain, and once I can write down those 13 steps, and I understand that code in each step, to write the code perfectly from memory becomes easy.

I hope you can tell that I love my journey into Deep Learning, and I wish you the same joy I find!
Feel free to email me improvements to this article at: DavidCode1@gmail.com